sonar.projectKey=scaleup
sonar.projectName=ScaleUp
sonar.projectVersion=1.1.0

sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests

sonar.exclusions=backend/venv/**,frontend/node_modules/**,frontend/dist/**,backend/storage/**,backend/bin/**,**/*.bin,**/*.param,**/*.mp4,**/*.zip,assets/**

sonar.sourceEncoding=UTF-8
